id = "quack"
name = "Quack"
version = "0.0.1"
schema_version = 1
authors = ["Mark Allen"]
description = "Quack language support for Zed"
repository = "https://github.com/quacklang/zed-quack"

[grammars.quack]
repository = "https://github.com/quacklang/tree-sitter-quack"
rev = "d569c14df642817c21da089e1e57135a41a0d583"
