id = "quack"
name = "Quack"
version = "0.0.1"
schema_version = 1
authors = ["Mark Allen"]
description = "Quack language support for Zed"
repository = "https://github.com/quacklang/zed-quack"

[grammars.quack]
repository = "https://github.com/quacklang/tree-sitter-quack"
rev = "624975a4ee83cd0e261a45e73cd3056a27fb4842"
